projects:
  SoftballStats:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: hrah63qjtvafnpciaowuhdduwm
      endpoints:
        prod: >-
          https://kn54uugqqzbbrnqt6jyyxufwq4.appsync-api.us-east-1.amazonaws.com/graphql
