const meetupData = {
    id: 'mu-123',
    date: '2019-01-01',
    gameId: '235',
    year: '2019',
    month: 'January',
    name: 'Game 235 @???? @ 1030am',
    field: 'Westlake Park',
    tournamentName: 'Halloween',
};

const currentGame = {
    date: 'today',
    field: 'Westlake',
    gameId: '300',
    lat: '111',
    lon: '111',
    id: 'zzz',
    month: 'Jan',
    name: 'MU',
    rsvps: '1',
    time: 'local time',
    timeStamp: 'time now',
    tournamentName: 'MU',
    waitListCount: '0',
    year: '2019',
};

const currentPlayerStats = [
    {
        id: '123',
        name: 'Fresh Basta',
        joined: 123,
        admin: false,
        status: 'active',
        gender: '',
        photos: 'http://photo',
        battingOrder: '1',
        o: '1',
        singles: '1',
        doubles: '1',
        triples: '1',
        hr: '1',
        rbi: '1',
        r: '2',
        sb: '1',
        cs: '0',
        k: '1',
        bb: '1',
        avg: '.600',
        ab: '1',
        tb: '1',
        rc: '.800',
        h: '1',
        sac: '1',
    },
    {
        id: '456',
        name: 'Steven',
        joined: 234,
        admin: true,
        status: 'active',
        gender: '',
        photos: 'http://photo',
        battingOrder: '1',
        o: '1',
        singles: '1',
        doubles: '1',
        triples: '1',
        hr: '1',
        rbi: '1',
        r: '1',
        sb: '1',
        cs: '0',
        k: '1',
        bb: '1',
        avg: '.200',
        ab: '1',
        tb: '1',
        rc: '.400',
        h: '1',
        sac: '1',
    },
];

const mergedPlayerStats = [
    {
        id: '123',
        name: 'Fresh Basta',
        joined: 123,
        admin: false,
        status: 'active',
        gender: 'n/a',
        photos: '{}',
        profile: '{}',
        games: [
            {
                ab: '1',
                battingOrder: '1',
                o: '1',
                singles: '1',
                doubles: '1',
                triples: '1',
                h: '1',
                hr: '1',
                rbi: '1',
                r: '2',
                sb: '1',
                cs: '0',
                k: '1',
                bb: '1',
                sac: '1',
                w: '1',
                l: '0',
                gp: '1',
                date: 'today',
                field: 'Westlake',
                lat: '111',
                lon: '111',
                month: 'Jan',
                name: 'MU',
                time: 'local time',
                timeStamp: 'time now',
                tournamentName: 'MU',
                year: '2019',
            },
        ],
    },
    {
        id: '456',
        name: 'Steven',
        joined: 234,
        admin: true,
        status: 'active',
        gender: 'n/a',
        photos: '{}',
        profile: '{}',
        games: [
            {
                ab: '1',
                battingOrder: '1',
                o: '1',
                singles: '1',
                doubles: '1',
                triples: '1',
                h: '1',
                hr: '1',
                rbi: '1',
                r: '1',
                sb: '1',
                cs: '0',
                k: '1',
                bb: '1',
                sac: '1',
                w: '0',
                l: '1',
                gp: '1',
                date: 'today',
                field: 'Westlake',
                lat: '111',
                lon: '111',
                month: 'Jan',
                name: 'MU',
                time: 'local time',
                timeStamp: 'time now',
                tournamentName: 'MU',
                year: '2019',
            },
        ],
    },
];

export default {
    currentGame,
    currentPlayerStats,
    meetupData,
    mergedPlayerStats,
}