const legacyData = [
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 48565492,
        name: 'Z-Dick',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 6,
        r: 2,
        singles: '0',
        doubles: '0',
        triples: '0',
        hr: 1,
        rbi: 4,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 97446312,
        name: 'Hamilton',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 7,
        r: 3,
        singles: 6,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 4119746,
        name: 'Judy',
        gender: 2,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 6,
        r: 3,
        singles: 4,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 110070632,
        name: 'Malou',
        gender: 2,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 5,
        r: 1,
        singles: 1,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: 1,
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 97463882,
        name: 'Marius',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 5,
        r: '0',
        singles: 2,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: 1,
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 9730562,
        name: 'Max',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 6,
        r: 1,
        singles: 1,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: 1,
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 12103018,
        name: 'Steven',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 7,
        r: 3,
        singles: 3,
        doubles: 1,
        triples: 1,
        hr: 1,
        rbi: 8,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 108835482,
        name: 'Troy Niekamp',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 17,
        ab: 4,
        r: 1,
        singles: '0',
        doubles: 1,
        triples: 2,
        hr: 1,
        rbi: '0',
        bb: 1,
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 1769896,
        name: 'Z-B. David',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 16,
        ab: 5,
        r: 4,
        singles: 2,
        doubles: 3,
        triples: '0',
        hr: '0',
        rbi: 3,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 117287402,
        name: 'Dan ',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 16,
        ab: 4,
        r: 1,
        singles: 1,
        doubles: '0',
        triples: '0',
        hr: 1,
        rbi: 3,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 97326752,
        name: 'Jay',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 16,
        ab: 4,
        r: 4,
        singles: 4,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: 1,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 8308191,
        name: 'Jim E',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 16,
        ab: 4,
        r: 1,
        singles: 1,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 97135242,
        name: 'Lauren Dickey',
        gender: 2,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 16,
        ab: 1,
        r: 1,
        singles: 1,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: 1,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 74058932,
        name: 'Z-Tim',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 16,
        ab: 2,
        r: 1,
        singles: 2,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/16/2013',
        time: '13:05:00',
        field: 'West Sunset',
        meetupId: 102839412,
        name: 'Joe',
        gender: 1,
        TEAM_1: 16,
        TEAM_2: 17,
        team: 16,
        ab: 2,
        r: 1,
        singles: 1,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 108496282,
        name: 'Matthew Greene',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: 2,
        singles: 1,
        doubles: 1,
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 20352781,
        name: 'James Lockwood',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: 4,
        singles: 1,
        doubles: 1,
        triples: '0',
        hr: 2,
        rbi: 7,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 97326752,
        name: 'Jay',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: 1,
        singles: 1,
        doubles: 2,
        triples: '0',
        hr: '0',
        rbi: 2,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 97446312,
        name: 'Hamilton',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: 2,
        singles: 1,
        doubles: 2,
        triples: '0',
        hr: '0',
        rbi: 2,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 118204792,
        name: 'HUBERT',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: 1,
        singles: 2,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 9730562,
        name: 'Max',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: '0',
        singles: 4,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 66865262,
        name: 'Vien Tang',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: '0',
        singles: 4,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: 2,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 110070632,
        name: 'Malou',
        gender: 2,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 5,
        r: 2,
        singles: 4,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 7348855,
        name: 'Peter',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 18,
        ab: 4,
        r: 2,
        singles: '0',
        doubles: 1,
        triples: 1,
        hr: 1,
        rbi: 3,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 97135242,
        name: 'Lauren Dickey',
        gender: 2,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 5,
        r: '0',
        singles: '0',
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 99539112,
        name: 'Debbie',
        gender: 2,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 4,
        r: '0',
        singles: '0',
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 102839412,
        name: 'Joe',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 5,
        r: 2,
        singles: 2,
        doubles: 1,
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 118280702,
        name: 'Natcha',
        gender: 2,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 5,
        r: 3,
        singles: 2,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 48565492,
        name: 'Z-Dick',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 5,
        r: 2,
        singles: 1,
        doubles: 1,
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 12103018,
        name: 'Steven',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 5,
        r: 2,
        singles: 1,
        doubles: 3,
        triples: '0',
        hr: '0',
        rbi: 2,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 6845441,
        name: 'John McCarthy',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 5,
        r: '0',
        singles: 4,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: 4,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 97463882,
        name: 'Marius',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 5,
        r: '0',
        singles: 2,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: 2,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 16113521,
        name: 'Jeremy Miller',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 4,
        r: '0',
        singles: 2,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: '0',
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
    {
        date: '11/23/2013',
        time: '10:30:00',
        field: 'West Sunset',
        meetupId: 111654162,
        name: 'Dale',
        gender: 1,
        TEAM_1: 18,
        TEAM_2: 19,
        team: 19,
        ab: 4,
        r: '0',
        singles: 2,
        doubles: '0',
        triples: '0',
        hr: '0',
        rbi: 1,
        bb: '0',
        k: '0',
        sac: '0',
        sb: '0',
    },
];

export { legacyData };
